---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(data.table)
 # Load Modified code
files <- list.files("../code/modified_source_code/", pattern = "\\.[rR]$", full.names = TRUE)
sapply(files, source, local = TRUE)
invisible(lapply(files, function(f) source(f, chdir = TRUE)))
source(knitr::purl("../../code/modified_source_code/Contracted_Fix_Main.Rmd", output = tempfile()))
```

```{R}
data.in <- read.csv("../../data/Data.df_for_new.sde_method2025-11-03.csv", check.names = FALSE) %>% select(-1)
```


```{r}
# Step 13: Same-Day Extraneous (SDE) logic
# Applied per subject and parameter (SP)
# Skips NNTEs.
data.df <- data.in %>% as.data.table()
data.df[exclude == 'Exclude-Temporary-Extraneous-Same-Day', exclude := 'Include']
setkey(data.df, subjid, param, agedays)
data.df[temporary_extraneous_infants(data.df), exclude := 'Exclude-Temporary-Extraneous-Same-Day']
data.df.subs <- data.df %>% group_by(subjid) %>% filter(any(exclude == "Exclude-Temporary-Extraneous-Same-Day")) %>% select(subjid) %>% distinct() %>% slice_sample(n=50)
data.df <- data.df %>% filter(subjid %in% data.df.subs$subjid)


data.df <- data.df %>%
  as.data.frame() %>%
  subset(valid(data.df, include.temporary.extraneous = TRUE) & nnte_full == FALSE) %>% 
  select(subjid, obsid = id, agedays, param, v, tbc.sd, exclude, nnte_full) %>% 
  group_by(subjid, param, agedays) %>% 
  mutate(sde_this = case_when(
             any(exclude == "Exclude-Temporary-Extraneous-Same-Day") ~ TRUE,
             TRUE ~ FALSE
           )) %>%
  arrange(subjid, param, agedays, obsid) %>% 
  group_by(subjid, param, agedays) %>% 
  mutate(length(unique(v)), 
             # B.
             # a.
             exclude = case_when(
               length(unique(v)) == 1 &
                 obsid != max(obsid, na.rm = TRUE)  ~ "Exclude-SDE-Identical",
               TRUE ~ exclude
             ),
             
             # b.
             dup_count = ave(v, v, FUN = length),
             exclude = case_when(
               dup_count > 1 &
                 obsid != max(obsid, na.rm = TRUE) &
                 exclude != "Include" ~ "Exclude-SDE-Identical",
               TRUE ~ exclude
             ),
             # C.
             # a.
             median_tbc = median(tbc.sd[exclude %in% c("Include", "Exclude-Temporary-Extraneous-Same-Day")], na.rm = TRUE),
             # b. 
             absdiff_rel_to_median = case_when(
               exclude %in% c("Include", "Exclude-Temporary-Extraneous-Same-Day") ~ abs(tbc.sd - median_tbc),
               TRUE ~ NA
             ),
             # c.
             median_tbc_lt2 = ifelse(min(absdiff_rel_to_median, na.rm = TRUE) > 2, TRUE, FALSE),
             exclude = ifelse(median_tbc_lt2 == TRUE, "Exclude-All-Extreme", exclude),
             # d.
             exclude = case_when(
               sum(exclude == "Include") == 1 &
                 exclude %in% c("Include") &
                 absdiff_rel_to_median != suppressWarnings(min(absdiff_rel_to_median[exclude %in% c("Include")], na.rm = TRUE)) ~ "Exclude-SDE-One-Day",
               TRUE ~ exclude)) %>% 
             # e. Regroup for tie-breaking logic, which requires inter-parameter checks.
             group_by(subjid, agedays) %>% 
             # f. Carry out logical checks.
             mutate(
                 HT_dop_med = ifelse(param == "HEIGHTCM", median(tbc.sd[exclude %in% c("Include") & param == "WEIGHTKG"], na.rm = TRUE), NA),
                 WT_dop_med = ifelse(param == "WEIGHTKG", median(tbc.sd[exclude %in% c("Include") & param == "HEIGHTCM"], na.rm = TRUE), NA),
                 absdiff_dop_med = case_when(
                   exclude %in% c("Include") & param == "HEIGHTCM" ~ abs(tbc.sd - HT_dop_med),
                   exclude %in% c("Include") & param == "WEIGHTKG" ~ abs(tbc.sd - WT_dop_med),
                   TRUE ~ NA
                 )) %>% 
                   group_by(subjid, param, agedays) %>%
                   mutate(
                   tied_vals = sum(exclude == "Include", na.rm = TRUE),
                   min_absdiff_dop_median = min(absdiff_dop_med, na.rm = TRUE),
                   n_min_dop = sum(exclude == "Include" & absdiff_dop_med == min_absdiff_dop_median, na.rm = TRUE),

                   exclude = 
                          case_when(exclude == "Include" & tied_vals > 1 &
                                      !is.na(absdiff_dop_med) & absdiff_dop_med != min_absdiff_dop_median ~ "Exclude-SDE-One-Day",
                                    TRUE ~ exclude),
              # g. obsid-based tiebreaker
                  tied_vals = sum(exclude == "Include", na.rm = TRUE),
                  exclude = case_when(
                    tied_vals > 1 &
                      exclude == "Include" &
                      obsid != max(obsid[exclude %in% c("Include")], na.rm = TRUE) ~ "Exclude-SDE-One-Day",
                    TRUE ~ exclude
                  )) %>% ungroup()
              # h. do i need to calculate this?
              # D. SDE-EWMAs
              # a. Calculate EWMA for full included vals
              ewma_df <- as.data.table(data.df %>% filter(exclude == "Include"))
              setkey(ewma_df, subjid, param, agedays)
              tmp <- data.frame(
                        "before" = abs(ewma_df$agedays - c(NA, ewma_df$agedays[1:(nrow(ewma_df)-1)])),
                        "after" = abs(ewma_df$agedays - c(ewma_df$agedays[2:(nrow(ewma_df))], NA))
                      )
              maxdiff <- sapply(1:nrow(tmp), function(x){max(tmp[x,], na.rm = TRUE)})
              exp_vals <- rep(-1.5, nrow(tmp))
              exp_vals[maxdiff > 365.25] <- -2.5
              exp_vals[maxdiff > 730.5] <- -3.5
              ewma.fields <- c('ewma.all', 'ewma.before', 'ewma.after')
              ewma_df[, (ewma.fields) := ewma(agedays, tbc.sd, exp_vals, TRUE)] %>% as.data.frame()
              data.df <- merge(data.df, ewma_df %>% 
                                 select(obsid, which(grepl("ewma", names(ewma_df)))), by = "obsid", all.x = TRUE)
              data.df <- data.df %>% 
                group_by(subjid, param, agedays) %>% 
                # b. Assign EWMAs to partially included vals.
                mutate(ewma.all = case_when(is.na(ewma.all) & exclude == "Exclude-Temporary-Extraneous-Same-Day" ~ max(ewma.all[exclude == "Include"], na.rm = TRUE),
                                            TRUE ~ ewma.all),
                                                                                 absdewma = abs(tbc.sd - ewma.all)) %>%  
                # c. If there's one fully or partially included value (n_min_absdewma == 1) with the lowest absdewma (absdewma == min_absdewma)
                mutate(
                  n_available = sum(exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include"), na.rm = TRUE),
                  min_absdewma = suppressWarnings(min(absdewma[exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include")],
                                                      na.rm = TRUE)),
                  min_absdewma = ifelse(is.infinite(min_absdewma), NA_real_, min_absdewma),
              
                  n_min_absdewma = sum(exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include") &
                                         absdewma == min_absdewma, na.rm = TRUE),
              
                  exclude = case_when(
                    n_available > 0 &
                      n_min_absdewma == 1 &
                      exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include") &
                      absdewma == min_absdewma ~ "Include",
                    n_available > 0 &
                      n_min_absdewma == 1 &
                      exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include") &
                      absdewma != min_absdewma ~ "Exclude-SDE-EWMA",
                    TRUE ~ exclude
                  ),
              
                  exclude = case_when(
                    n_available > 0 &
                      n_min_absdewma > 1 &
                      exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include") &
                      absdewma == min_absdewma &
                      obsid == max(obsid[absdewma == min_absdewma &
                                         exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include")],
                                   na.rm = TRUE) ~ "Include",
                    n_available > 0 &
                      n_min_absdewma > 1 &
                      exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include") &
                      absdewma == min_absdewma &
                      obsid != max(obsid[absdewma == min_absdewma &
                                         exclude %in% c("Exclude-Temporary-Extraneous-Same-Day",
                                                  "Include")],
                                   na.rm = TRUE) ~ "Exclude-SDE-EWMA",
                    TRUE ~ exclude
                    
                  ),
                  exclude = ifelse(exclude == "Exclude-Temporary-Extraneous-Same-Day", "Exclude-SDE-EWMA", exclude)
                
                ) %>%
                ungroup()

               

table(data.df$exclude)

# View(data.df)
```

```{r}
# TEsting New SDE Code:

library(growthcleanr)
library(dplyr)
library(data.table)
library(dplyr)
library(data.table)
library(stringr)
library(gt)

# Load Modified code
files <- list.files("../../code/modified_source_code/", pattern = "\\.[rR]$", full.names = TRUE)
sapply(files, source, local = TRUE)
invisible(lapply(files, function(f) source(f, chdir = TRUE)))
source(knitr::purl("../../code/modified_source_code/Contracted_Fix_Main.Rmd", output = tempfile()))

data.in <- as.data.table(data.in)
setkey(data.in, subjid, param, agedays)
cleaned_data_updated <- cleangrowth(
  subjid = data.in$subjid,
  param = data.in$param,
  agedays = data.in$agedays,
  sex = data.in$sex,
  measurement = data.in$v,
  prelim_infants = TRUE,
  id = data.in$id, 
  sd.recenter = "nhanes"
)

```
