---
title: "R Notebook"
output: html_notebook
---

```{r}
library(growthcleanr)
library(dplyr)
library(data.table)
library(dplyr)
library(data.table)
library(stringr)
library(gt)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(include = FALSE, echo = FALSE, eval = TRUE)
```

#### Helper Functions
```{r}
map_to_stata <- function(x) {
  case_when(
    # --- Carry-forward family ---
    x == "Exclude-1-CF-deltaZ-<0.05" ~ "1 CF deltaZ <0.05",
    x == "Exclude-1-CF-deltaZ-<0.1-wholehalfimp" ~ "1 CF imperial deltaZ <0.1",
    x == "Exclude-Teen-2-plus-CF-deltaZ-<0.05" ~ "Carried forward",
    x == "Exclude-Carried-Forward" ~ "Carried forward",

    # --- Measurement count flags ---
    x == "Exclude-1-meas" ~ "1 meas",
    x == "Exclude-2-meas-<1-year" ~ "2 meas <1 year",
    x == "Exclude-2-meas->1-year" ~ "2 meas >1 year",

    # --- Biologically implausible values ---
    x == "Exclude-Absolute-BIV" ~ "Absolute BIV",
    x == "Exclude-Standardized-BIV" ~ "Standardized BIV",

    # --- EWMA steps ---
    x == "Exclude-EWMA1-Extreme" ~ "EWMA1 high sum",
    x == "Exclude-EWMA2-middle" ~ "EWMA2 middle",
    x == "Exclude-EWMA2-first" ~ "EWMA2 first",
    x == "Exclude-EWMA2-first-ext" ~ "EWMA2 first ext",
    x == "Exclude-EWMA2-last" ~ "EWMA2 last",
    x == "Exclude-EWMA2-birth-HT-HC" ~ "EWMA2 birth HT HC",
    x == "Exclude-EWMA2-birth-HT-HC-ext" ~ "EWMA2 birth HT HC ext",
    x == "Exclude-EWMA2-birth-WT" ~ "EWMA2 birth WT",

    # --- Evil twins step ---
    x == "Exclude-Evil-Twins" ~ "Evil Twins",

    # --- Diff-based flags ---
    x == "Exclude-Min-diff" ~ "Min diff",
    x == "Exclude-Max-diff" ~ "Max diff",

    # --- SDEs (same-day extraneous) ---
    x == "Exclude-SDE-All-Exclude" ~ "SDE-All-Exclude",
    x == "Exclude-SDE-All-Extreme" ~ "SDE-Extreme",
    x == "Exclude-SDE-EWMA" ~ "SDE-EWMA",
    x == "Exclude-SDE-Identical" ~ "SDE-Identical",
    x == "Exclude-SDE-One-Day" ~ "SDE-One-Day",

    # --- Miscellaneous / other ---
    x == "Include" ~ "Include",
    x == "Exclude-Error-load" ~ "Error load",

    TRUE ~ x
  )
}

print_table <- function(tbl){
# build gt table with conditional coloring
gt(tbl) %>%
  fmt_number(columns = "n", sep_mark = ",") %>%
  
  # column 1 always green
  data_color(
    columns = c(gcr_result_carrie),
    fn = function(x) rep("#6FCF97", length(x))
  ) %>%
  
  # column 2: green if matches col1, orange otherwise
  data_color(
    columns = c(gcr_result_cp),
    rows = gcr_result_cp == gcr_result_carrie,
    fn = function(x) rep("#6FCF97", length(x))
  ) %>%
  data_color(
    columns = c(gcr_result_cp),
    rows = gcr_result_cp != gcr_result_carrie,
    fn = function(x) rep("#F2994A", length(x))
  ) %>%
  
  # column 3: same logic
  data_color(
    columns = c(gcr_result_cp_updated),
    rows = gcr_result_cp_updated == gcr_result_carrie,
    fn = function(x) rep("#6FCF97", length(x))
  ) %>%
  data_color(
    columns = c(gcr_result_cp_updated),
    rows = gcr_result_cp_updated != gcr_result_carrie,
    fn = function(x) rep("#F2994A", length(x))
  ) %>%
  data_color(
    columns = c(gcr_result_cp_updated),
    rows = gcr_result_cp == gcr_result_carrie & gcr_result_cp_updated != gcr_result_cp,
    fn = function(x) rep("maroon", length(x))
  )
}

# **Pausing Code to Evaluate Changes Thus Far**
```
1. Generate Baseline - STATA vs. Unmodified R Code
```{R, eval = FALSE}
# Let's evaluate the baseline GC (i.e., unmodified source files) against the modified code, strictly in terms of gcr_result only.
files <- list.files("../../R/", pattern = "\\.[rR]$", full.names = TRUE)
sapply(files, source, local = TRUE)
invisible(lapply(files, function(f) source(f, chdir = TRUE)))
# Load in STATA output:
stata_gc_in <- data.table::fread("../data/2025-10-25-gc-Stata-chopd1p-results.csv")

data.work <- stata_gc_in %>% select(
  id = obsid,
  subjid,
  param,
  sex,
  agedays,
  param,
  measurement,
  exc_wt,
  exc_ht,
  potcorr,
  tbcwtz,
  ctbcwtz
) %>% mutate(param = case_when(
  param == "Weight" ~ "WEIGHTKG",
  param == "Height" ~ "HEIGHTCM",
  TRUE ~ param
)) %>% filter(param %in% c("WEIGHTKG", "HEIGHTCM"))

data.work <- data.work %>% mutate(gcr_result_carrie = case_when(
  param == "WEIGHTKG" ~ exc_wt,
  param == "HEIGHTCM" ~ exc_ht,
  TRUE ~ "ERR"
)) %>% select(-c(exc_wt, exc_ht)) 
# data.work <- data.work  %>% filter(subjid %in% Merged_Maps_sub$subjid.x)

data.work <- as.data.table(data.work)
setkey(data.work, subjid, param, agedays)
cleaned_data <- data.work[,gcr_result_cp := cleangrowth(subjid, param, agedays, sex, measurement, prelim_infants = TRUE,  sd.recenter = "nhanes")]
# View(cleaned_data %>% filter(subjid == "444336"))
# Baseline_Characteristics_Table

# write.csv(cleaned_data, "../data/baseline_comparison_of_stata_vs_R_2025-10-28.csv")
Baseline_Characteristics_Table <- cleaned_data %>% select(gcr_result_carrie, gcr_result_cp, id, subjid) %>% mutate(gcr_result_cp = gsub("^Exclude", "", gcr_result_cp),
                                gcr_result_cp = gsub("-", " ", gcr_result_cp),
                                gcr_result_cp = str_trim(gcr_result_cp),
                                gcr_result_carrie = tolower(gcr_result_carrie),
                                gcr_result_cp = tolower(gcr_result_cp),
                                results_pasted = paste(gcr_result_carrie, gcr_result_cp, sep = " ; "))
table(Baseline_Characteristics_Table$results_pasted)
# Baseline_Characteristics_Table <- as.data.frame(table(Baseline_Characteristics_Table$results_pasted)) %>% arrange(desc(Freq))
# write.csv(Baseline_Characteristics_Table, paste("../deliverables/Baseline_Characteristics_Table", Sys.Date(), ".csv", sep = ""))
```

2. Generate Current - STATA vs. Modified R Code

```{r}
# Load Modified code
files <- list.files("../code/modified_source_code/", pattern = "\\.[rR]$", full.names = TRUE)
sapply(files, source, local = TRUE)
invisible(lapply(files, function(f) source(f, chdir = TRUE)))
source(knitr::purl("../code/modified_source_code/Contracted_Fix_Main.Rmd", output = tempfile()))
# Load in STATA output:
stata_gc_in <- data.table::fread("../data/2025-10-01-gc-Stata-chopd1p-results.csv")

data.work <- stata_gc_in %>% select(
  id,
  subjid,
  param,
  sex,
  agedays,
  param,
  measurement,
  exc_wt,
  exc_ht,
  potcorr,
  tbcwtz,
  ctbcwtz
) %>% mutate(param = case_when(
  param == "Weight" ~ "WEIGHTKG",
  param == "Height" ~ "HEIGHTCM",
  TRUE ~ param
)) %>% filter(param %in% c("WEIGHTKG", "HEIGHTCM"))

data.work <- data.work %>% mutate(gcr_result_carrie = case_when(
  param == "WEIGHTKG" ~ exc_wt,
  param == "HEIGHTCM" ~ exc_ht,
  TRUE ~ "ERR"
)) %>% select(-c(exc_wt, exc_ht)) 
data.work <- as.data.table(data.work)
setkey(data.work, subjid, param, agedays)
cleaned_data_updated <- cleangrowth(
  subjid = data.work$subjid,
  param = data.work$param,
  agedays = data.work$agedays,
  sex = data.work$sex,
  measurement = data.work$measurement,
  prelim_infants = TRUE,
  id = data.work$id, sd.recenter = "nhanes"
)

# write.csv(cleaned_data_updated, paste("../data/Checkpoint_Updated_R_", Sys.Date(), ".csv", sep = ""))

Modified_Characteristics_Table <- merge(data.work %>% select(id, gcr_result_carrie), cleaned_data_updated %>% select(id, exclude), by = "id")

# Modified_Characteristics_Table
Modified_Characteristics_Table <- Modified_Characteristics_Table %>% select(gcr_result_carrie, gcr_result_cp_updated = exclude) %>% mutate(gcr_result_cp_updated = gsub("^Exclude", "", gcr_result_cp_updated),
                                gcr_result_cp_updated = gsub("-", " ", gcr_result_cp_updated),
                                gcr_result_cp_updated = str_trim(gcr_result_cp_updated),
                                gcr_result_carrie = tolower(gcr_result_carrie),
                                gcr_result_cp_updated = tolower(gcr_result_cp_updated),
                                results_pasted = paste(gcr_result_carrie, gcr_result_cp_updated, sep = " ; "))

Modified_Characteristics_Table <- as.data.frame(table(Modified_Characteristics_Table$results_pasted)) %>% arrange(desc(Freq))
# write.csv(Modified_Characteristics_Table, paste("../deliverables/Modified_Characteristics_Table", Sys.Date(), ".csv", sep = ""))
```

```{r}
Baseline_Map <- read.csv("../data/baseline_comparison_of_stata_vs_R_2025-10-28.csv") %>% select(id, gcr_result_carrie, gcr_result_cp)
Updated_Map <- read.csv("../data/Checkpoint_Updated_R_2025-10-22.csv") %>% select(id, gcr_result_cp_updated = exclude)
Updated_Map <- cleaned_data_updated %>% select(id, gcr_result_cp_updated = exclude)
Merged_Maps <- merge(Baseline_Map, Updated_Map, by = "id")


map_to_stata <- function(x) {
  case_when(
    # --- Carry-forward family ---
    x == "Exclude-1-CF-deltaZ-<0.05" ~ "1 CF deltaZ <0.05",
    x == "Exclude-1-CF-deltaZ-<0.1-wholehalfimp" ~ "1 CF imperial deltaZ <0.1",
    x == "Exclude-Teen-2-plus-CF-deltaZ-<0.05" ~ "Carried forward",
    x == "Exclude-Carried-Forward" ~ "Carried forward",

    # --- Measurement count flags ---
    x == "Exclude-1-meas" ~ "1 meas",
    x == "Exclude-2-meas-<1-year" ~ "2 meas <1 year",
    x == "Exclude-2-meas->1-year" ~ "2 meas >1 year",

    # --- Biologically implausible values ---
    x == "Exclude-Absolute-BIV" ~ "Absolute BIV",
    x == "Exclude-Standardized-BIV" ~ "Standardized BIV",

    # --- EWMA steps ---
    x == "Exclude-EWMA1-Extreme" ~ "EWMA1 high sum",
    x == "Exclude-EWMA2-middle" ~ "EWMA2 middle",
    x == "Exclude-EWMA2-first" ~ "EWMA2 first",
    x == "Exclude-EWMA2-first-ext" ~ "EWMA2 first ext",
    x == "Exclude-EWMA2-last" ~ "EWMA2 last",
    x == "Exclude-EWMA2-birth-HT-HC" ~ "EWMA2 birth HT HC",
    x == "Exclude-EWMA2-birth-HT-HC-ext" ~ "EWMA2 birth HT HC ext",
    x == "Exclude-EWMA2-birth-WT" ~ "EWMA2 birth WT",

    # --- Evil twins step ---
    x == "Exclude-Evil-Twins" ~ "Evil Twins",

    # --- Diff-based flags ---
    x == "Exclude-Min-diff" ~ "Min diff",
    x == "Exclude-Max-diff" ~ "Max diff",

    # --- SDEs (same-day extraneous) ---
    x == "Exclude-SDE-All-Exclude" ~ "SDE-All-Exclude",
    x == "Exclude-SDE-All-Extreme" ~ "SDE-Extreme",
    x == "Exclude-SDE-EWMA" ~ "SDE-EWMA",
    x == "Exclude-SDE-Identical" ~ "SDE-Identical",
    x == "Exclude-SDE-One-Day" ~ "SDE-One-Day",

    # --- Miscellaneous / other ---
    x == "Include" ~ "Include",
    x == "Exclude-Error-load" ~ "Error load",

    TRUE ~ "Unmapped"
  )
}

# Apply mapping to both columns
Merged_Maps <- Merged_Maps %>%
  mutate(
    gcr_result_cp = map_to_stata(gcr_result_cp),
    gcr_result_cp_updated = map_to_stata(gcr_result_cp_updated)
  )

library(networkD3)
library(dplyr)

Merged_Maps <- Merged_Maps %>% filter(gcr_result_carrie!=gcr_result_cp)

library(gt)
Merged_Maps %>%
  count(gcr_result_carrie, gcr_result_cp, gcr_result_cp_updated) %>%
  arrange(desc(n)) %>%
  gt::gt() %>%
  gt::fmt_number(columns = "n", sep_mark = ",")



```

```{R}
# According to this, there are still problems with over-flagging SDE one days on rows which are included in the stata.

Baseline_Map <- read.csv("../data/baseline_comparison_of_stata_vs_R_2025-10-07.csv") %>% select(id, gcr_result_carrie, gcr_result_cp)
Updated_Map <- read.csv("../data/Checkpoint_Updated_R_2025-10-14.csv")
datsel <- merge(Baseline_Map, Updated_Map, by = "id", all = TRUE) %>% group_by(subjid) %>% filter(any(gcr_result_carrie == "1 CF imperial deltaZ <0.1" & exclude == "Exclude-Carried-Forward"))
View(datsel)

SOIs<- unique(datsel$subjid)
```

#### TEST BLOCK
```{R, include = TRUE}
library(growthcleanr)
library(dplyr)
library(data.table)
library(dplyr)
library(data.table)
library(stringr)
library(gt)

# Load Modified code
files <- list.files("../code/modified_source_code/", pattern = "\\.[rR]$", full.names = TRUE)
sapply(files, source, local = TRUE)
invisible(lapply(files, function(f) source(f, chdir = TRUE)))
source(knitr::purl("../code/modified_source_code/Contracted_Fix_Main.Rmd", output = tempfile()))

# Load in STATA output:
stata_gc_in <- data.table::fread("../data/2025-10-01-gc-Stata-chopd1p-results.csv")
stata_gc_in_sde_pats <- stata_gc_in %>% group_by(subjid) %>% filter(any(grepl("SDE", exc_ht) | grepl("SDE", exc_wt))) %>% select(subjid) %>% distinct() 
data.work <- stata_gc_in %>% 
  select(
  id ,
  subjid,
  param,
  sex,
  agedays,
  param,
  measurement,
  exc_wt,
  exc_ht,
  potcorr,
  tbcwtz,
  ctbcwtz
) %>%
  mutate(param = case_when(
  param == "Weight" ~ "WEIGHTKG",
  param == "Height" ~ "HEIGHTCM",
  TRUE ~ param
)) %>% filter(param %in% c("WEIGHTKG", "HEIGHTCM"))

data.work <- data.work %>% mutate(gcr_result_carrie = case_when(
  param == "WEIGHTKG" ~ exc_wt,
  param == "HEIGHTCM" ~ exc_ht,
  TRUE ~ "ERR"
)) %>% select(-c(exc_wt, exc_ht)) 

data.work <- data.work %>% filter(subjid %in% stata_gc_in_sde_pats$subjid)

data.work <- as.data.table(data.work)
setkey(data.work, subjid, param, agedays)
cleaned_data_updated <- cleangrowth(
  subjid = data.work$subjid,
  param = data.work$param,
  agedays = data.work$agedays,
  sex = data.work$sex,
  measurement = data.work$measurement,
  prelim_infants = TRUE,
  id = data.work$id, 
  sd.recenter = "nhanes"
)

# write.csv(cleaned_data_updated, paste("../data/Checkpoint_Updated_R_", Sys.Date(), ".csv", sep = ""))

Modified_Characteristics_Table <- merge(data.work, cleaned_data_updated %>% select(id, exclude), by = "id")

# Modified_Characteristics_Table
Modified_Characteristics_Table <- Modified_Characteristics_Table %>% select(gcr_result_carrie, gcr_result_cp_updated = exclude) %>% mutate(gcr_result_cp_updated = gsub("^Exclude", "", gcr_result_cp_updated),
                                gcr_result_cp_updated = gsub("-", " ", gcr_result_cp_updated),
                                gcr_result_cp_updated = str_trim(gcr_result_cp_updated),
                                gcr_result_carrie = tolower(gcr_result_carrie),
                                gcr_result_cp_updated = tolower(gcr_result_cp_updated),
                                results_pasted = paste(gcr_result_carrie, gcr_result_cp_updated, sep = " ; "))

Modified_Characteristics_Table <- as.data.frame(table(Modified_Characteristics_Table$results_pasted)) %>% arrange(desc(Freq))
# write.csv(Modified_Characteristics_Table, paste("../deliverables/Modified_Characteristics_Table", Sys.Date(), ".csv", sep = ""))
# Modified_Characteristics_Table

Baseline_Map <- read.csv("../data/baseline_comparison_of_stata_vs_R_2025-10-07.csv") %>% select(id, gcr_result_carrie, gcr_result_cp, subjid)

cleaned_data_updated <- read.csv("../data/Checkpoint_Updated_R_2025-10-22.csv")

Updated_Map <- cleaned_data_updated %>% select(id, subjid, gcr_result_cp_updated = exclude)

Merged_Maps <- merge(Baseline_Map, Updated_Map, by = "id")

# Apply mapping to both columns
Merged_Maps <- Merged_Maps %>%
  mutate(
    gcr_result_cp = map_to_stata(gcr_result_cp),
    gcr_result_cp_updated = map_to_stata(gcr_result_cp_updated)
  )

# summarise the data
tbl <- Merged_Maps %>%
  count(gcr_result_carrie, gcr_result_cp, gcr_result_cp_updated) %>%
  arrange(desc(n))

print_table(tbl)


IDs_of_interest <- Merged_Maps %>% filter(gcr_result_carrie == "Include" &
                         gcr_result_cp == "Include" & 
                         gcr_result_cp_updated == "Carried forward") 

# View(cleaned_data_updated %>% filter(subjid %in% IDs_of_interest$subjid.x))
```

```{R}
# Cases where stata flags as ewma first ext but R include = many were where agedays was actually 0. Issue with STATA. Double-checking.
```

```{r}
IDs_of_interest_ewma_first <- Merged_Maps %>% filter(gcr_result_carrie == "EWMA2 first ext" &
                         gcr_result_cp == "Include" & 
                         gcr_result_cp_updated == "Include") 
View(cleaned_data_updated %>% filter(subjid %in% IDs_of_interest_ewma_first$subjid.x) %>% mutate(row_of_interest = ifelse(id %in% IDs_of_interest_ewma_first$id, 1, 0)))
ewmafirstextagedays0_issues <- cleaned_data_updated %>% filter(subjid %in% IDs_of_interest_ewma_first$subjid.x) %>% mutate(row_of_interest = ifelse(id %in% IDs_of_interest_ewma_first$id, 1, 0)) %>% filter(row_of_interest == 1) %>% select(subjid, id, exclude)
# write.csv(ewmafirstextagedays0_issues, "../data/Ewma2FirstExtOverFlags_agedays0.csv")
ewmafirstextagedays0_issues


```

```{r}
stata_new <- read.csv("../data/2025-10-25-gc-Stata-chopd1p-results.csv") %>% mutate(exclude = case_when(param == "HEIGHTCM" ~ exc_ht, 
                                                                                           param == "WEIGHTKG" ~ exc_wt,
                                                                                           TRUE ~ NA)) %>% select(subjid, obsid, exclude, agedays, param)
stata_new %>% filter(subjid %in% IDs_of_interest_ewma_first$subjid.x)  %>% filter(agedays == 0)
```

